# Generated by Django 4.0.1 on 2022-01-26 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_comment_date_alter_video_date_upload_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='label',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='videotag',
            old_name='Video',
            new_name='video',
        ),
    ]
