# Generated by Django 4.0.1 on 2022-01-30 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_watch_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
