# Generated by Django 4.0.1 on 2022-02-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_banner_image_alter_logo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logo',
            name='channel',
        ),
        migrations.AddField(
            model_name='channel',
            name='banner',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='channel',
            name='logo',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.DeleteModel(
            name='Logo',
        ),
    ]
